# Generated by Django 2.2 on 2019-04-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='choice_text',
            new_name='comment_text',
        ),
    ]
